### ISSUE TITLE
Implement timed token exchange with Classroom

### ISSUE THREAD

**Issue by srinjoym** [education/classroom-assistant#46]
Already implemented on Classroom with https://github.com/education/classroom/pull/1450
Need to add support on Classroom Desktop side.

### TODO:
- [x] Refactor `userAuthentication.js` to go to Classroom API instead of GitHub OAuth
- [x] Store access token in keytar
- [x] Use token in all requests to Classroom API
- [x] Automatically redirect users to `populate` page if user is logged in
- [x] Migrate to `http` node module for all requests in renderer process to avoid CORS issues
- [x] Testing testing testing
