### ISSUE TITLE
Update Styling to match Classroom

### ISSUE THREAD

**Issue by srinjoym** [education/classroom-assistant#49]
### TODO:
- [x] New Splash Screen
- [x] New Assignment Header throughout UI
- [x] Logout Button in Header
- [x] Update auth window to go to Classroom API
- [x] New icons for Labels
- [x] Overall Progress Bar for Archive Window
