### ISSUE TITLE
Add Release Scripts on CI

### ISSUE THREAD

**Issue by srinjoym** [education/classroom-assistant#50]
Need to build on all three operating operating systems for electron forge packaging to work

### TODO:
- [x] Get Mac Developer Certificate
- [x] Encrypt Developer Certificate in Travis CI?
- [x] Setup AppVeyor Builds for Windows (https://github.com/education/classroom-desktop/issues/36)
- [x] Configure CI to publish to GitHub releases
- [x] Get Windows certificate
