### ISSUE TITLE
Switch to Dugite for cloning

### ISSUE THREAD

**Issue by srinjoym** [education/classroom-assistant#52]
Update: NodeGit is also a pain to build on Windows because of issues with node-gyp. Pushing priority of this up for MVP Release because it'll require more often to figure out how to get NodeGit to work instead of just switching to Dugite.

Nodegit is causing significant performance bottlenecks when cloning multiple repositories. Dugite is a package with native git bindings for Electron that was developed by the GitHub team.

### TODO:
- [x] Refactor `cloneutils.js` for Dugite
- [x] Parse system output and callback with progress
- [x] Measure performance against nodegit
- [x] Fix submission folder bug
- [x] Add tests for Progress Parser
