### ISSUE TITLE
Windows Styling Issues

### ISSUE THREAD

**Issue by srinjoym** [education/classroom-assistant#60]
### TODO
- [x] Remove toolbar for dragging when not on Mac
- [x] Remove extra width causing the scroll bar to appear
- [x] Cleanup helper shortcuts
- [x] Get Squirell Installation GIF
