### ISSUE TITLE
Replace URL box with Autocomplete Search Bar 

### ISSUE THREAD

**Issue by srinjoym** [education/classroom-assistant#96]
Replace the URL entry box on the populate page with an autocomplete search bar similar to what we have on Classroom for Starter Code

### TODO
- [x] Implement API endpoints to fetch assignments for user on Classroom 
- [ ] Search over all classrooms user has
- [ ] Show list of classrooms in UI
